### ISSUE TITLE
Add new tool: Bandage

### ISSUE THREAD

**Issue by skchronicles** [OpenOmics/assembly-seek#5]
## About

Add a new summarization tool: Bandage. This tool is not installed on Biowulf; however, this looks like a GUI-driven application. We need to get more clarity on how it is going to be used. Are you just creating the input files for this application?

**Github:** https://rrwick.github.io/Bandage/

**Comment by asyakhl** [comment]
it is only GUI.   AGB is alternative to Bandage which could be added to Snakemake.
